#!/usr/bin/env python3
"""Generate the org token files from tokens/tokens.json.

tokens.json is the design system's token file (the JakobMelchard Design System artifact) and
the one source of the org palette. This is the one generator; it writes, next to itself:

  tokens.css    custom properties only: colors, shadows and color-scheme per theme under
                [data-theme], everything else on :root. Web UIs vendor it (config-sync,
                opt-in .config/tokens.path) or import @jakobmelchard/config/tokens.css.
  tokens.swift  enum GeneratedTokens (dark theme colours, px radii). Apple apps vendor it
                (config-sync, opt-in .config/tokens-swift.path).

Both are committed; CI regenerates and fails on a diff. Stdlib only. Edit tokens.json, run
this, commit as feat: (or fix:). Never edit the outputs by hand. Only targets with a consumer
exist here: add one when a repo needs it.
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "tokens.json"
CSS = ROOT / "tokens.css"
SWIFT = ROOT / "tokens.swift"

BANNER = "generated by tokens/build_tokens.py from tokens/tokens.json ({name} v{version})"
THEMED = ("color", "shadow")
SKIP = {"name", "version", "meta", "type"} | set(THEMED)


# CSS ---------------------------------------------------------------------------------------


def pretty(v):
    """Match prettier: `rgba(1, 2, 3, 0.5)`, so regenerating is idempotent under a consumer's format check."""
    def args(m):
        parts = [a.strip() for a in m.group(2).split(",")]
        parts = [re.sub(r"^(-?)\.(\d)", r"\g<1>0.\2", a) for a in parts]
        return f"{m.group(1)}({', '.join(parts)})"
    return re.sub(r"\b(rgba?|hsla?)\(([^)]*)\)", args, v)


def val(token, theme, first):
    v = token["value"]
    if isinstance(v, dict):
        v = v.get(theme, v.get(first))
    if isinstance(v, str) and v.startswith("{") and v.endswith("}"):
        return f"var(--{v[1:-1]})"
    return pretty(v)


def block(selector, lines, props=()):
    body = "".join(f"  {n}: {v};\n" for n, v in props) + "".join(f"  --{n}: {v};\n" for n, v in lines)
    return f"{selector} {{\n" + body + "}\n"


def css(t):
    themes = [th["id"] for th in t["color"]["themes"]]
    first = themes[0]
    out = ["/* " + BANNER.format(name=t["name"], version=t["version"]) + " */\n"]

    for i, theme in enumerate(themes):
        lines = [(tok["name"], val(tok, theme, first)) for fam in THEMED if fam in t for tok in t[fam]["tokens"]]
        sel = f":root,\n[data-theme='{theme}']" if i == 0 else f"[data-theme='{theme}']"
        # color-scheme so UA widgets, scrollbars and form controls follow the theme
        scheme = [("color-scheme", theme)] if theme in ("dark", "light") else []
        out.append(block(sel, lines, scheme))

    root = [(tok["name"], tok["value"]) for fam, body in t.items() if fam not in SKIP and isinstance(body, dict) and "tokens" in body for tok in body["tokens"]]
    fams = t["type"]["families"]
    root += [(f"font-{k}", v) for k, v in fams.items()]
    if "mono" in fams:
        root.append(("font", "var(--font-mono)"))  # legacy name the sites use
    out.append(block(":root", root))
    return "\n".join(out), len(root)


# Swift -------------------------------------------------------------------------------------


def camel(name):
    head, *rest = name.split("-")
    return head + "".join(p[:1].upper() + p[1:] for p in rest)


def parse_color(v, name):
    """`#rrggbb` or `rgba(r,g,b,a)` -> (0xRRGGBB int, alpha str or None). Alpha keeps its source digits."""
    if re.fullmatch(r"#[0-9a-fA-F]{6}", v):
        return int(v[1:], 16), None
    m = re.fullmatch(r"rgba\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(-?[\d.]+)\s*\)", v)
    if m:
        r, g, b = (int(x) for x in m.groups()[:3])
        a = m.group(4)
        a = "0" + a if a.startswith(".") else a
        return (r << 16) | (g << 8) | b, a
    sys.exit(f"build_tokens: color token {name!r} has unsupported value {v!r} (want #rrggbb or rgba())")


def colors(t, theme):
    """[(name, ("alias", target) | ("rgb", 0xRRGGBB, alpha))] for one theme, in tokens.json order."""
    themes = [th["id"] for th in t["color"]["themes"]]
    out, seen = [], set()
    for tok in t["color"]["tokens"]:
        name, v = tok["name"], tok["value"]
        if isinstance(v, dict):
            v = v.get(theme, v.get(themes[0]))
        if v.startswith("{") and v.endswith("}"):
            target = v[1:-1]
            if target not in seen:
                sys.exit(f"build_tokens: alias {name!r} -> {target!r} must come after its target")
            out.append((name, ("alias", target)))
        else:
            out.append((name, ("rgb", *parse_color(v, name))))
        seen.add(name)
    return out


def radii(t):
    """radius-* tokens with a px value, as (name, number str); percentages have no native form."""
    out = []
    for tok in t.get("radius", {}).get("tokens", []):
        m = re.fullmatch(r"(\d+(?:\.\d+)?)px", tok["value"])
        if m:
            out.append((tok["name"], m.group(1)))
    return out


def swift(t):
    out = ["// Code " + BANNER.format(name=t["name"], version=t["version"]) + ". DO NOT EDIT.\n", "\nimport SwiftUI\n\n"]
    out.append("/// Dark-theme colour tokens and px radii, one per token in tokens.json. `Theme` exposes them.\n")
    out.append("enum GeneratedTokens {\n")
    for name, c in colors(t, "dark"):
        if c[0] == "alias":
            expr = camel(c[1])
        else:
            expr = f"Color(hex: 0x{c[1]:06X})" + (f".opacity({c[2]})" if c[2] is not None else "")
        out.append(f"  static let {camel(name)} = {expr}\n")
    out.append("\n")
    for name, px in radii(t):
        out.append(f"  static let {camel(name)}: CGFloat = {px}\n")
    out.append("}\n")
    return "".join(out)


def main():
    t = json.loads(SRC.read_text())
    text, nroot = css(t)
    CSS.write_text(text)
    SWIFT.write_text(swift(t))
    print(f"wrote {CSS.name} and {SWIFT.name}: {nroot} root, {sum(len(t[f]['tokens']) for f in THEMED if f in t)} themed x {len(t['color']['themes'])} themes")


if __name__ == "__main__":
    main()
